import io
import json
import zipfile
from datetime import datetime

import joblib
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse

from app.core.deps import get_current_user
from app.core.ownership import require_owner
from app.database.models import User
from app.services.persistence.model_loader import load_saved_model

router = APIRouter(prefix="/export", tags=["Export"])


README_TEMPLATE = """MLForge model export
=====================

Dataset : {display_name}
Model   : {model_name} ({algorithm})
Version : {version}
Problem : {problem_type}
Target  : {target_column}
Exported: {exported_at}

Files in this archive
----------------------
model.pkl          The trained scikit-learn estimator (joblib format).
pipeline.pkl       The fitted preprocessing pipeline (imputation, scaling,
                    encoding). Always transform new data with this BEFORE
                    calling model.predict - it was fit only on the
                    training split, so it is safe to reuse without leakage.
label_encoder.pkl  Only present for classification models. Use it to
                    convert the model's numeric output back into the
                    original class labels.
feature_names.json The encoded feature names the model expects, in order,
                    after the pipeline has transformed the raw input.
metadata.json      Training metadata: algorithm, target column, raw input
                    schema, and performance at export time.
evaluation.json    The full evaluation report (metrics, confusion matrix
                    reference, etc.) from the training run.

Minimal usage example (Python)
-------------------------------
    import joblib
    import pandas as pd

    model = joblib.load("model.pkl")
    pipeline = joblib.load("pipeline.pkl")

    # raw_row must contain the same raw columns MLForge asked for at
    # prediction time - see metadata.json -> "input_schema" for the list.
    raw_row = pd.DataFrame([{{"feature_1": ..., "feature_2": ...}}])

    X = pipeline.transform(raw_row)
    prediction = model.predict(X)

    try:
        label_encoder = joblib.load("label_encoder.pkl")
        prediction = label_encoder.inverse_transform(prediction)
    except FileNotFoundError:
        pass  # regression model - no label encoder to invert

    print(prediction)

Generated by MLForge. Developed by Pranav Kumar.
"""


@router.get("/{dataset_name}/{model_name}")
def export_model(
    dataset_name: str,
    model_name: str,
    current_user: User = Depends(get_current_user),
):
    """
    Download the production version of a trained model as a self-contained
    zip: the model, its preprocessing pipeline, label encoder (if any),
    feature names, metadata, and evaluation report - everything needed to
    run inference outside of MLForge.
    """
    require_owner(dataset_name, current_user.id)

    try:
        artifacts = load_saved_model(
            dataset_name=dataset_name,
            model_name=model_name,
            version="production",
        )
    except FileNotFoundError:
        raise HTTPException(
            status_code=404,
            detail=f"No trained model named '{model_name}' was found for dataset '{dataset_name}'.",
        )

    metadata = artifacts["metadata"]

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zf:

        model_bytes = io.BytesIO()
        joblib.dump(artifacts["model"], model_bytes)
        zf.writestr("model.pkl", model_bytes.getvalue())

        pipeline_bytes = io.BytesIO()
        joblib.dump(artifacts["pipeline"], pipeline_bytes)
        zf.writestr("pipeline.pkl", pipeline_bytes.getvalue())

        if artifacts["label_encoder"] is not None:
            le_bytes = io.BytesIO()
            joblib.dump(artifacts["label_encoder"], le_bytes)
            zf.writestr("label_encoder.pkl", le_bytes.getvalue())

        zf.writestr("feature_names.json", json.dumps(artifacts["feature_names"], indent=2))
        zf.writestr("metadata.json", json.dumps(metadata, indent=2))
        zf.writestr("evaluation.json", json.dumps(artifacts["evaluation"], indent=2))

        zf.writestr(
            "README.txt",
            README_TEMPLATE.format(
                display_name=metadata.get("display_name", dataset_name),
                model_name=metadata.get("model_name", model_name),
                algorithm=metadata.get("algorithm", "unknown"),
                version=metadata.get("version", "unknown"),
                problem_type=metadata.get("problem_type", "unknown"),
                target_column=metadata.get("target_column", "unknown"),
                exported_at=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            ),
        )

    buffer.seek(0)

    display_name = metadata.get("display_name", dataset_name)
    safe_model = model_name.replace(" ", "_")
    filename = f"{display_name}_{safe_model}.zip"

    return StreamingResponse(
        buffer,
        media_type="application/zip",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
